### ISSUE TITLE
GetAssignment issues

### ISSUE THREAD

**Issue by chriscastille6** [cloudyr/MTurkR#122]
I have a dataset of 121 people on Mturk for a particular HIT Id. When I use the following code:
a <- as.data.frame(GetAssignment(hit.type = [HIT ID Kept anonymous], return.all=TRUE))

My software locks up. I've traced this issue to using the "return.all=TRUE" function. If I switch that to "FALSE", then I can only pull 101 participants.

Any idea what could be the problem?

**Comment by leeper** [comment]
What do you mean by "locks up"? Does it just take a long time or does R actually crash?

**Comment by solstice** [comment]
I have a similar issue. When I run the command `GetAssignments(hit.type = MYHITTYPEID, return.all = TRUE)`, I get this error repeatedly:

```
Request NA not valid for API request:
https://mechanicalturk.sandbox.amazonaws.com/?Service = AWSMechanicalTurkRequester
                                             &AWSAccessKeyId = REDACTED
                                             &SortDirection = Ascending 


Error (ServiceUnavailable):
  Service AWSMechanicalTurkRequester is currently unavailable. Please try again later
```

When I use the command without the `return.all` option, it returns all assignments related to the HIT type ID.

Also, when I use `hit` instead of `hit.type`, specifying the `return.all = TRUE` option also returns all assignments related to this specific HIT.

 I am using this in the sandbox.
